Use lowercase variable in bash loop.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -183,9 +183,9 @@ jobs:
               ansible-role-tinypilot
               ansible-role-ustreamer
             )
-            for ANSIBLE_ROLE in "${ANSIBLE_ROLES[@]}"; do
-              if [[ ! -d "${ANSIBLE_ROLE}" ]]; then
-                >&2 echo "Bundle is missing Ansible role: ${ANSIBLE_ROLE}"
+            for ansible_role in "${ANSIBLE_ROLES[@]}"; do
+              if [[ ! -d "${ansible_role}" ]]; then
+                >&2 echo "Bundle is missing Ansible role: ${ansible_role}"
                 exit 1
               fi
             done
