check force install flag. restrict installs to RPi 4B, bullseye 32-bit

diff --git a/bundler/bundle/install b/bundler/bundle/install
--- a/bundler/bundle/install
+++ b/bundler/bundle/install
@@ -11,45 +11,52 @@ set -u
 # Echo commands before executing them, by default to stderr.
 set -x
 
-# Prevent installation on the Raspberry Pi 3.
-if grep -q "^Model *: Raspberry Pi 3" /proc/cpuinfo ; then
-  echo 'You are trying to install on incompatible hardware.' >&2
-  echo 'Visit https://github.com/tiny-pilot/tinypilot/ for more details.' >&2
-  exit 1
-fi
-
-# Prevent installation on 64-bit operating systems.
-# Note: the distro ID is called "Raspbian" because the 32-bit version of the
-# Raspberry Pi operating system is based on Raspbian repos (an independent
-# open-source project). Similarly, the the 64-bit version of the Raspberry Pi
-# operating system is based on Debian and its distro ID would be "Debian".
-if [[ "$(lsb_release --id --short)" != 'Raspbian' ]]; then
-  echo "TinyPilot currently only supports the 32-bit version of Raspberry Pi OS 11 \"Bullseye\" " >&2
-  echo "To install TinyPilot, you'll need to install Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
-  exit 1
-fi
-
-# Prevent installation on OS versions lower than Raspberry Pi OS 11 "Bullseye".
-if (( "$(lsb_release --release --short)" < 11 )); then
-  echo "TinyPilot no longer supports Raspberry Pi OS 10 \"Buster\" or lower." >&2
-  echo "To install TinyPilot, you'll need to upgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
-  exit 1
-fi
-
-# Prevent installation on Raspberry Pi OS 12 "Bookworm".
-if (( "$(lsb_release --release --short)" > 11 )); then
-  echo "TinyPilot is not yet compatible with Raspberry Pi OS 12 \"Bookworm\"." >&2
-  echo "You can track our progress by visiting https://github.com/tiny-pilot/tinypilot/issues/1668" >&2
-  echo "To install TinyPilot, you'll need to downgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
-  exit 1
-fi
-
-# Abort installation if the read-only filesystem is enabled
+# Abort installation if the read-only filesystem is enabled.
 if grep -q "boot=overlay" /proc/cmdline ; then
   echo 'The read-only filesystem is enabled.' >&2
   echo 'Disable the read-only filesystem before proceeding.' >&2
   echo 'See https://tinypilotkvm.com/faq/read-only-filesystem for details.' >&2
   exit 1
+fi
+
+# Check if the user is forcing an install.
+if [[ -z "${FORCE_INSTALL+x}" ]]; then
+  # Restrict installation to only specific configurations.
+
+  # Install only on Raspberry Pi 4 Model B.
+  if ! grep --quiet "^Model\s*: Raspberry Pi 4 Model B" /proc/cpuinfo ; then
+    echo 'You are trying to install on incompatible hardware.' >&2
+    echo 'Visit https://github.com/tiny-pilot/tinypilot/ for more details.' >&2
+    exit 1
+  fi
+
+  # Prevent installation on 64-bit operating systems.
+  # Note: the distro ID is called "Raspbian" because the 32-bit version of the
+  # Raspberry Pi operating system is based on Raspbian repos (an independent
+  # open-source project). Similarly, the the 64-bit version of the Raspberry Pi
+  # operating system is based on Debian and its distro ID would be "Debian".
+  if [[ "$(lsb_release --id --short)" != 'Raspbian' ]]; then
+    echo "TinyPilot currently only supports the 32-bit version of Raspberry Pi OS 11 \"Bullseye\" " >&2
+    echo "To install TinyPilot, you'll need to install Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
+    exit 1
+  fi
+
+  # Prevent installation on OS versions lower than Raspberry Pi OS 11 "Bullseye".
+  if (( "$(lsb_release --release --short)" < 11 )); then
+    echo "TinyPilot no longer supports Raspberry Pi OS 10 \"Buster\" or lower." >&2
+    echo "To install TinyPilot, you'll need to upgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
+    exit 1
+  fi
+
+  # Prevent installation on Raspberry Pi OS 12 "Bookworm".
+  if (( "$(lsb_release --release --short)" > 11 )); then
+    echo "TinyPilot is not yet compatible with Raspberry Pi OS 12 \"Bookworm\"." >&2
+    echo "You can track our progress by visiting https://github.com/tiny-pilot/tinypilot/issues/1668" >&2
+    echo "To install TinyPilot, you'll need to downgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
+    exit 1
+  fi
+elif (( "${FORCE_INSTALL}" == 1 )); then
+  echo 'Forcing installation on unsupported setup.'
 fi
 
 # Get the filename of the Janus Debian package.
