Remove trailing punctuation.

diff --git a/bundler/bundle/install b/bundler/bundle/install
--- a/bundler/bundle/install
+++ b/bundler/bundle/install
@@ -34,7 +34,7 @@ fi
 if [[ "$(lsb_release --id --short)" == 'Raspbian' ]] \
     && (( "$(lsb_release --release --short)" > 11 )); then
   echo "TinyPilot is not yet compatible with Raspberry Pi OS 12 \"Bookworm\"." >&2
-  echo "You can track our progress by visiting https://github.com/tiny-pilot/tinypilot/issues/1668." >&2
+  echo "You can track our progress by visiting https://github.com/tiny-pilot/tinypilot/issues/1668" >&2
   echo "To install TinyPilot, you'll need to downgrade your operating system to Raspberry Pi OS 11 \"Bullseye\"." >&2
   exit 1
 fi
