Move up pre-condition check

diff --git a/bundler/create-bundle b/bundler/create-bundle
--- a/bundler/create-bundle
+++ b/bundler/create-bundle
@@ -20,6 +20,12 @@ readonly ANSIBLE_ROLE_TINYPILOT_VERSION='master'
 readonly BUNDLE_DIR='bundle'
 readonly OUTPUT_DIR='dist'
 
+# Ensure that a TinyPilot Debian package exists.
+if ! ls "${BUNDLE_DIR}/tinypilot"*.deb 1> /dev/null 2>&1; then
+  echo 'Failed to create bundle: no TinyPilot Debian package found.' >&2
+  exit 1
+fi
+
 # Prints the TinyPilot release version as populated in the Debian package. The
 # Debian package stores the version string in a header field of its control
 # file. The header is named: `Tinypilot-Version`.
@@ -53,12 +59,6 @@ python3 -m venv venv
 # instead of building the packages locally.
 pip install "pip>=21.3.1"
 pip install --requirement "${BUNDLE_DIR}/requirements.txt"
-
-# Ensure that a TinyPilot Debian package exists.
-if ! ls "${BUNDLE_DIR}/tinypilot"*.deb 1> /dev/null 2>&1; then
-  echo 'Failed to create bundle: no TinyPilot Debian package found.' >&2
-  exit 1
-fi
 
 # Install Ansible role dependencies.
 ansible-galaxy install \
