Make Debian package authoritative for generating version string (#1229)
Part of https://github.com/tiny-pilot/gatekeeper/issues/108.

Currently, we generate the version string of the TinyPilot release
redundantly: first when creating the Debian package, and then again when
creating the bundle. We wanted to make the Debian package authoritative
for generating the version string, to reduce the odds of
inconsistencies, so the bundler now reads the version string from the
Debian package.

Some notes:

- The `XBS-` prefix is [an internal, build-time directive for
user-defined
fields](https://www.debian.org/doc/debian-policy/ch-controlfields.html#user-defined-fields).
It’s stripped in the eventual package.
- Debian headers are case-insensitive, but by convention they are
printed with capitalized words. So `TinyPilot-Version` (uppercase “P”)
would be printed as `Tinypilot-Version` (lowercase “P”). Therefore, I
thought we can write it like that right away, to avoid confusion, even
though I would have preferred the camel-cased variant. I’m not sure we
need to add a comment about that – it might not be directly obvious, but
on the other hand [it’s documented on Debian’s
end](https://www.debian.org/doc/debian-policy/ch-controlfields.html#syntax-of-control-files),
and it also might not be *that* important.
- Unfortunately, `lintian` complains about our custom header. It’s just
a warning, but we [also fail the build on
warnings](https://github.com/tiny-pilot/tinypilot/blob/437adc28e4a956be13bc994d23d278b4ca7fd31b/.circleci/config.yml#L120).
I couldn’t find a way to allow individual headers fine-granularly.
Suppressing the `unknown-field` lintian tag is a bit of a sledge-hammer
approach, but I can only think of one alternative right now, which is to
extract the package archive to a ephemeral, temporary directory, and
then read the `/opt/tinypilot/VERSION` file. I find that rather
inelegant, though, and I also think it could be useful to have the
canonical version info baked into the Debian header directly. (E.g.
[when printing info about an installed package via `apt
show`](https://user-images.githubusercontent.com/83721279/207090044-03c52f83-926f-4472-9fa1-bd7d7503af24.png).)

<a data-ca-tag
href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1229"><img
src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review
on CodeApprove" /></a>

diff --git a/bundler/create-bundle b/bundler/create-bundle
--- a/bundler/create-bundle
+++ b/bundler/create-bundle
@@ -20,6 +20,26 @@ readonly ANSIBLE_ROLE_TINYPILOT_VERSION='master'
 readonly BUNDLE_DIR='bundle'
 readonly OUTPUT_DIR='dist'
 
+# Ensure that a TinyPilot Debian package exists.
+if ! ls "${BUNDLE_DIR}/tinypilot"*.deb 1> /dev/null 2>&1; then
+  echo 'Failed to create bundle: no TinyPilot Debian package found.' >&2
+  exit 1
+fi
+
+# Prints the TinyPilot release version as populated in the Debian package. The
+# Debian package stores the version string in a header field of its control
+# file. The header is named: `Tinypilot-Version`.
+print_tinypilot_version() {
+  # Shellcheck incorrectly warns that the `${...}` placeholder in `--showformat`
+  # doesn’t expand, due to the single-quotes. The format string is not meant to
+  # contain a bash variable, though, the placeholder is specific to `dpkg-deb`.
+  # shellcheck disable=SC2016
+  dpkg-deb \
+    --show \
+    --showformat '${Tinypilot-Version}' \
+    "${BUNDLE_DIR}/tinypilot"*.deb
+}
+
 # Compose bundle file name, which consists of these hyphen-separated parts:
 # 1. `tinypilot`
 # 2. The TinyPilot variant: `community` or `pro`
@@ -31,7 +51,7 @@ readonly OUTPUT_DIR='dist'
 # - `tinypilot-pro-20220620T1713Z-2.4.1.tgz` (Pro)
 TIMESTAMP="$(date --iso-8601=minutes | sed 's/[:-]//g' | sed 's/+0000/Z/g')"
 readonly TIMESTAMP
-TINYPILOT_VERSION="$(git rev-parse --short HEAD)"
+TINYPILOT_VERSION="$(print_tinypilot_version)"
 readonly TINYPILOT_VERSION
 readonly TINYPILOT_VARIANT='community'
 readonly BUNDLE_FILENAME="tinypilot-${TINYPILOT_VARIANT}-${TIMESTAMP}-${TINYPILOT_VERSION}.tgz"
@@ -42,12 +62,6 @@ python3 -m venv venv
 # instead of building the packages locally.
 pip install "pip>=21.3.1"
 pip install --requirement "${BUNDLE_DIR}/requirements.txt"
-
-# Ensure that a TinyPilot Debian package exists.
-if ! ls "${BUNDLE_DIR}/tinypilot"*.deb 1> /dev/null 2>&1; then
-  echo 'Failed to create bundle: no TinyPilot Debian package found.' >&2
-  exit 1
-fi
 
 # Install Ansible role dependencies.
 ansible-galaxy install \
