Replace the right check

diff --git a/bundler/verify-bundle b/bundler/verify-bundle
--- a/bundler/verify-bundle
+++ b/bundler/verify-bundle
@@ -35,14 +35,14 @@ tar \
   --directory "${BUNDLE_DIR}"
 pushd "${BUNDLE_DIR}"
 
-# List Debian package contents.
-dpkg --contents tinypilot*.deb
-
-# Check that Debian package exists.
-if ! ls tinypilot*.deb 1> /dev/null 2>&1; then
-  >&2 echo 'Bundle is missing Debian package.'
+# Check that install script exists.
+if [[ ! -f install ]]; then
+  >&2 echo 'Bundle is missing install script.'
   exit 1
 fi
+
+# List Debian package contents.
+dpkg --contents tinypilot*.deb
 
 # Check that Ansible roles exist.
 readonly ANSIBLE_ROLES=(
