Refactor exit trap.

diff --git a/scripts/install-bundle b/scripts/install-bundle
--- a/scripts/install-bundle
+++ b/scripts/install-bundle
@@ -78,9 +78,21 @@ FREE_MEMORY_MIB="$(free --mebi |
   cut --delimiter ' ' --fields 4)"
 readonly FREE_MEMORY_MIB
 
+INSTALLER_DIR='/mnt/tinypilot-installer'
+
+# Remove temporary files & directories.
+clean_up() {
+  umount --lazy "${INSTALLER_DIR}" || true
+  rm -rf \
+    "${LEGACY_INSTALLER_DIR}" \
+    "${INSTALLER_DIR}"
+}
+
+# Always clean up before exiting.
+trap 'clean_up' EXIT
+
 if (( "${FREE_MEMORY_MIB}" >= "${RAMDISK_SIZE_MIB}" )); then
   # Mount volatile RAMdisk.
-  INSTALLER_DIR='/mnt/tinypilot-installer'
   sudo mkdir "${INSTALLER_DIR}"
   sudo mount \
     --types tmpfs \
@@ -93,17 +105,6 @@ else
   INSTALLER_DIR="$(mktemp --directory)"
 fi
 readonly INSTALLER_DIR
-
-# Remove temporary files & directories.
-clean_up() {
-  umount --lazy "${INSTALLER_DIR}" || true
-  rm -rf \
-    "${LEGACY_INSTALLER_DIR}" \
-    "${INSTALLER_DIR}"
-}
-
-# Always clean up before exiting.
-trap 'clean_up' EXIT
 
 # Extract tarball to installer directory.
 tar \
