renamed variable to context

diff --git a/dev-scripts/check-for-init-py-files b/dev-scripts/check-for-init-py-files
--- a/dev-scripts/check-for-init-py-files
+++ b/dev-scripts/check-for-init-py-files
@@ -11,9 +11,9 @@ set -u
 
 success=0
 
-while read -r line; do
-  if [ ! -f "$line/__init__.py" ]; then
-    printf "Directory missing __init__.py file: %s\n" "${line}" >&2
+while read -r directory; do
+  if [ ! -f "$directory/__init__.py" ]; then
+    printf "Directory missing __init__.py file: %s\n" "${directory}" >&2
     success=255
   fi
 done < <(
