Apply shellcheck recommendations.

diff --git a/dev-scripts/check-trailing-whitespace b/dev-scripts/check-trailing-whitespace
--- a/dev-scripts/check-trailing-whitespace
+++ b/dev-scripts/check-trailing-whitespace
@@ -7,12 +7,15 @@ set -e
 # Exit on unset variable.
 set -u
 
-if grep \
-  "\s$" \
-  --line-number \
-  --binary-files=without-match \
-  --exclude="*third-party*" \
-  $(git ls-files | xargs); then
-  echo "ERROR: Found trailing whitespace";
-  exit 1;
-fi
+while read -r line; do
+  if grep \
+    "\s$" \
+    --line-number \
+    --with-filename \
+    --binary-files=without-match \
+    --exclude="*third-party*" \
+    "${line}"; then
+    echo "ERROR: Found trailing whitespace";
+    exit 1;
+  fi
+done < <(git ls-files)
